### ISSUE TITLE
Check power status using HTTP API.

### ISSUE THREAD

**Issue by OrangeTux** [OrangeTux/einder#1]
When the device is powered a resource is available on `<ip>:62137/DeviceDescription.xml`. This resource is not available when the set-top box is powered off. It can be used to check the power status of the device.

**Comment by namebee** [comment]
Hello @OrangeTux, I've been trying Einder out and so far it has been working but I've noticed this doesn't work anymore. Is there any workaround?

**Comment by OrangeTux** [comment]
Hello @HeyItsMeNobody. I don't have a set-top box anymore, so I'm not sure if I can help you. But nonetheless, what is the problem?

**Comment by namebee** [comment]
The problem is that :62137/DeviceDescription.xml doesn't exist anymore. Not when the box is off, on or running an app.

**Comment by OrangeTux** [comment]
Than I'm afraid I cannot help you. Maybe an firmware update changed the API of the set-top box.

**Comment by benleb** [comment]
@OrangeTux sorry, hopefully its okay to post this here...

@HeyItsMeNobody you can give [horimote](https://github.com/benleb/horimote) a try. It is developed for the german Unitymedia Horizon HD Recorder but that seems to be the same device :)
