### ISSUE TITLE
Commands are continuously sent

### ISSUE THREAD

**Issue by OnnoH** [OrangeTux/einder#7]
When issueing a send_key or power_on data is continuously set, leaving the box in an undesirable state. Debug log suggests that the client is disconnected. Powering off using the switch is the only way out :-(

EDIT:
It repeats the last key send over and over.

I used a similar script in PHP which works.

**Comment by benleb** [comment]
Can you supply some more information? Logs, traces, ... ?
I am heavily using this lib since month or even years on different devices and never saw a similar behaviour. ✌️

**Comment by OnnoH** [comment]
The logs are consistent.
```
DEBUG:einder.client:Connected with set-top box at xxx.xxx.xxx.xxx:5900.
DEBUG:einder.client:Authorized succesfully with set-top box at xxx.xxx.xxx.xxx:5900.
DEBUG:einder.client:Set-top box at xxx.xxx.xxx.xxx:5900 is powered off.
DEBUG:einder.client:Closed connection with with set-top box at xxx.xxx.xxx.xxx:5900.
```
I didn't expect this behaviour either. The PHP script does the same thing: open socket, write to socket, close socket.

I'm using Python3. Might that be the culprit?

My Samsung device is rebranded Ziggo Mediabox XL with the Horizon logo in the gateway UI. Access is on gatewayIP + 1 on Home Network. Media Sharing enabled to allow for remote power ON/OFF.

**Comment by totospix** [comment]
I am having the same issue with my Horizon Box. Not constantly, but about every 10th sending. I have tried the Java-Version, same not constantly issue. Seems that some Horizon-Boxes are working different.

**Comment by OnnoH** [comment]
Uptil now the aforementioned PHP script works like it should. As I said the code is quite similar. Once you have a sort of workaround, it's hard to spend time diving into this issue. ;-)

**Comment by Christopher2000** [comment]
I think this is a timing issue. I've had this happen when using c.send_key without time.sleep before and after.  So currently my code looks like this:

c = Client("<IP>", port=5900)
time.sleep(0.5)
c.send_key(keys.<Command>)
time.sleep(0.5)
c.disconnect()

I haven't tested with shorter sleep times or leaving one of the sleep statements out. But I've sent this command many times without the mediabox failing.
